#!/bin/bash
set -eo pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# Read inputs
payload=$(mktemp /tmp/resource-out.XXXXXX)
cat > "$payload" <&0

current_revision=$(jq -r '.version.revision // "none"' < "$payload")

jq -n \
--arg revision "$current_revision" \
'[
  { revision: $revision }
]' >&3
